### PR TITLE
allow standard es6 import

### LINKED ISSUE #12: Feature request : make srt-parser-2 compatible with ES6 module 'import'
Please could you update srt-parser-2 to make it compatible with ES6-pure implementations which would use
`import srt from 'srt-parser-2'` to import the parser.

### PR DESCRIPTION
**Pull request by uriva**
Mind making sure it actually works? I don't have ts experience (tests pass)

closes #12

### CODE REVIEW

**Comment by 1c7** [comment]
The current version is `1.1.7`.
I am gonna publish `1.1.8`
Thanks for the PR

**Comment by 1c7** [comment]
oh testing.

**Comment by 1c7** [comment]
I am gonna test and release a new version on NPM in the next couple day.

**Comment by 1c7** [comment]
1.1.8 has release

**Comment by uriva** [comment]
works for me yay

**Pull request merged**
